
services:
  db:
    image: mysql:9.1.0
    # command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: rest_with_spring_boot_erudio
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - erudio-network
  rest-with-spring-boot-erudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: lucasb0nnet/rest-with-spring-boot-erudio
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin 
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - erudio-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - partainer_data:/data
    networks:
      - erudio-network

volumes:
  partainer_data:
networks:
  erudio-network:
    driver: bridge


