
services:
  db:
    image: mysql:9.1.0
    # command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: rest_with_spring_boot_erudio
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - erudio-network
  rest-with-spring-boot-erudio:
    build:
      context: ./rest-with-spring-boot-and-java-erudio
      dockerfile: Dockerfile
    image: lucasb0nnet/rest-with-spring-boot-erudio
    restart: always
    build: ./rest-with-spring-boot-and-java-erudio
    working_dir: /rest-with-spring-boot-and-java-erudio
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin 
    command: mvn spring-boot:run
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge


